name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get GitHub account/organization
      run: echo ::set-env name=ORG::$(dirname ${GITHUB_REPOSITORY})
    - name: Echo account/organization
      run: echo ${ORG}
